### ISSUE TITLE
I got a error saying : An error has occurred: xdelta3: target window checksum mismatch: XD3_INVALID_INPUT

### ISSUE THREAD

**Issue by masontheidiotlol** [AGO061/BuckshotRouletteModLoader#2] opened 2024-02-11 03:25 UTC
idk how to fix it i just got the error and cant fix

**Comment by AGO061** [comment] 2024-02-11 09:35
> idk how to fix it i just got the error and cant fix

Are you using the itch.io version or a pirated version of the game?

**Comment by AGO061** [comment] 2024-02-11 09:52
Also, possible duplicate of https://github.com/AGO061/BuckshotRouletteModLoader/issues/1

**Comment by NotHyper-474** [comment] 2024-02-11 13:48
If you downloaded from itch.io try re-downloading it

**Comment by AGO061** [comment] 2024-02-12 11:11
I'll close this for now as it's probably a duplicate, feel free to open a new issue if it persists

**Closed** 2024-02-12 11:11 UTC

**Comment by Apollucas** [comment] 2024-05-27 15:07
I'm getting this error also, but I'm using the Steam version.

**Comment by MSLaFaver** [comment] 2024-05-29 03:44
@Apollucas Are you using the BRML_setup.exe installer or the brml2.xdelta file? Could you check to make sure you have the latest version installed (1.2.2) and are using the latest files from GitHub?

**Comment by Apollucas** [comment] 2024-05-29 12:19
@MSLaFaver I'm using the brml2_linux.xdelta file, and I'm running the latest Linux version (should've clarified that earlier, sorry), which is also 1.2.2. I've also done a fresh pull on the GitHub repo to try again, to no avail.

**Comment by MSLaFaver** [comment] 2024-05-29 19:42
@Apollucas Thanks for letting me know! Steam pushed out Hotfix 4 and didn't tell anyone. The installer and xdelta patches are working now!

**Comment by Apollucas** [comment] 2024-05-29 19:57
@MSLaFaver You're welcome, glad to be of help! :)

**Comment by ominoussage** [comment] 2024-10-01 13:22
I have the exact same problem and circumstances as @Apollucas and it's not working for me. This is the error I have:

```
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
```

I'm using Fedora Silverblue 39.
